name: Go

on:
  pull_request:
    branches: [ "master", "main" ]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v -race ./...

    - name: Build
      run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12
